version: '3'

services:
  db:
    image: mongo:4.0-xenial
    container_name: ${APP_NAME}_db
    hostname: ${APP_NAME}_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      default:
    ports:
      - ${DOCKER_BRIDGE}:${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./docker/db/mongodb:/var/lib/mongodb
    restart: always

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}