version: '3'

services:
  db:
    image: bitnami/mongodb:4.0
    container_name: ${APP_NAME}_db
    hostname: ${APP_NAME}_db
    environment:
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_DATABASE: ${MONGO_DATABASE}
    networks:
      default:
    ports:
      - ${MONGO_ADDRESS}:${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./docker/db/mongodb:/var/lib/mongodb:rw
      - ./docker/db/mongodata:/data/db:rw
    restart: always

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}